import type { Kysely } from 'kysely'
import type { Database } from '../schema/database'

export const id = '20260704_001'
export const name = 'initial_graph_domain_schema'

export async function up(db: Kysely<Database>): Promise<void> {
  await db.schema.createTable('schema_migrations').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('name','text',(c)=>c.notNull()).addColumn('applied_at','text',(c)=>c.notNull()).execute()
  await db.schema.createTable('users').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('email','text').addColumn('display_name','text').addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createIndex('idx_users_deleted_at').ifNotExists().on('users').column('deleted_at').execute()

  await db.schema.createTable('graph_nodes').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('node_type','text',(c)=>c.notNull()).addColumn('title','text',(c)=>c.notNull()).addColumn('summary','text').addColumn('visibility','text',(c)=>c.notNull().defaultTo('private')).addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createIndex('idx_graph_nodes_user_type_deleted').ifNotExists().on('graph_nodes').columns(['user_id','node_type','deleted_at']).execute()
  await db.schema.createIndex('idx_graph_nodes_user_visibility_deleted').ifNotExists().on('graph_nodes').columns(['user_id','visibility','deleted_at']).execute()

  await db.schema.createTable('graph_edges').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('source_node_id','text',(c)=>c.notNull().references('graph_nodes.id')).addColumn('target_node_id','text',(c)=>c.notNull().references('graph_nodes.id')).addColumn('edge_type','text',(c)=>c.notNull()).addColumn('label','text').addColumn('weight','integer').addColumn('position','integer').addColumn('metadata_json','text').addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createIndex('idx_graph_edges_source').ifNotExists().on('graph_edges').columns(['user_id','source_node_id','edge_type','deleted_at']).execute()
  await db.schema.createIndex('idx_graph_edges_target').ifNotExists().on('graph_edges').columns(['user_id','target_node_id','edge_type','deleted_at']).execute()
  await db.schema.createIndex('idx_graph_edges_type').ifNotExists().on('graph_edges').columns(['user_id','edge_type','deleted_at']).execute()
  await db.schema.createIndex('uniq_graph_edges_active').ifNotExists().unique().on('graph_edges').columns(['user_id','source_node_id','target_node_id','edge_type']).where('deleted_at' as any,'is',null).execute()

  await db.schema.createTable('videos').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('node_id','text',(c)=>c.notNull().unique().references('graph_nodes.id')).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('source_url','text',(c)=>c.notNull()).addColumn('canonical_url','text').addColumn('source_platform','text',(c)=>c.notNull().defaultTo('other')).addColumn('external_id','text').addColumn('title','text').addColumn('description','text').addColumn('thumbnail_url','text').addColumn('creator_name','text').addColumn('duration_seconds','integer').addColumn('progress','text',(c)=>c.notNull().defaultTo('saved')).addColumn('learning_state','text',(c)=>c.notNull().defaultTo('none')).addColumn('importance','integer').addColumn('raw_metadata_json','text').addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createIndex('idx_videos_user_progress_deleted').ifNotExists().on('videos').columns(['user_id','progress','deleted_at']).execute()
  await db.schema.createIndex('idx_videos_identity_known').ifNotExists().on('videos').columns(['user_id','source_platform','external_id']).execute()
  await db.schema.createIndex('idx_videos_identity_canonical').ifNotExists().on('videos').columns(['user_id','canonical_url']).execute()

  await db.schema.createTable('topics').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('node_id','text',(c)=>c.notNull().unique().references('graph_nodes.id')).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('name','text',(c)=>c.notNull()).addColumn('description','text').addColumn('parent_topic_id','text',(c)=>c.references('topics.id')).addColumn('sort_order','integer',(c)=>c.notNull().defaultTo(0)).addColumn('is_system','integer',(c)=>c.notNull().defaultTo(0)).addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createIndex('idx_topics_parent').ifNotExists().on('topics').columns(['user_id','parent_topic_id','deleted_at']).execute()

  await db.schema.createTable('skills').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('node_id','text',(c)=>c.notNull().unique().references('graph_nodes.id')).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('topic_id','text',(c)=>c.references('topics.id')).addColumn('name','text',(c)=>c.notNull()).addColumn('description','text').addColumn('difficulty','text').addColumn('status','text',(c)=>c.notNull().defaultTo('not_started')).addColumn('is_system','integer',(c)=>c.notNull().defaultTo(0)).addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createIndex('idx_skills_topic').ifNotExists().on('skills').columns(['user_id','topic_id','deleted_at']).execute()

  await db.schema.createTable('notes').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('node_id','text',(c)=>c.notNull().unique().references('graph_nodes.id')).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('parent_node_id','text',(c)=>c.notNull().references('graph_nodes.id')).addColumn('body','text',(c)=>c.notNull()).addColumn('timestamp_seconds','integer').addColumn('note_type','text',(c)=>c.notNull().defaultTo('plain')).addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createIndex('idx_notes_parent').ifNotExists().on('notes').columns(['user_id','parent_node_id','deleted_at']).execute()

  await db.schema.createTable('drills').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('node_id','text',(c)=>c.notNull().unique().references('graph_nodes.id')).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('title','text',(c)=>c.notNull()).addColumn('description','text').addColumn('instructions','text').addColumn('difficulty','text').addColumn('duration_minutes','integer').addColumn('repetition_target','integer').addColumn('status','text',(c)=>c.notNull().defaultTo('planned')).addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createTable('mistakes').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('node_id','text',(c)=>c.notNull().unique().references('graph_nodes.id')).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('title','text',(c)=>c.notNull()).addColumn('description','text').addColumn('correction','text').addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createTable('tags').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('node_id','text',(c)=>c.notNull().unique().references('graph_nodes.id')).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('name','text',(c)=>c.notNull()).addColumn('color','text').addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createIndex('idx_tags_name').ifNotExists().on('tags').columns(['user_id','name','deleted_at']).execute()

  await db.schema.createTable('learning_paths').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('node_id','text',(c)=>c.notNull().unique().references('graph_nodes.id')).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('title','text',(c)=>c.notNull()).addColumn('description','text').addColumn('status','text',(c)=>c.notNull().defaultTo('active')).addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createTable('learning_path_items').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('path_id','text',(c)=>c.notNull().references('learning_paths.id')).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('item_node_id','text',(c)=>c.notNull().references('graph_nodes.id')).addColumn('position','integer',(c)=>c.notNull()).addColumn('completed_at','text').addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createTable('collections').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('node_id','text',(c)=>c.notNull().unique().references('graph_nodes.id')).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('title','text',(c)=>c.notNull()).addColumn('description','text').addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createTable('collection_items').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('collection_id','text',(c)=>c.notNull().references('collections.id')).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('item_node_id','text',(c)=>c.notNull().references('graph_nodes.id')).addColumn('position','integer',(c)=>c.notNull()).addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()

  await db.schema.createTable('inbox_items').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('source_url','text').addColumn('canonical_url','text').addColumn('shared_title','text').addColumn('shared_text','text').addColumn('source_platform','text',(c)=>c.notNull().defaultTo('other')).addColumn('raw_payload_json','text').addColumn('status','text',(c)=>c.notNull().defaultTo('new')).addColumn('converted_node_id','text',(c)=>c.references('graph_nodes.id')).addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createIndex('idx_inbox_user_status').ifNotExists().on('inbox_items').columns(['user_id','status','deleted_at']).execute()

  await db.schema.createTable('share_links').ifNotExists().addColumn('id','text',(c)=>c.primaryKey()).addColumn('user_id','text',(c)=>c.notNull().references('users.id')).addColumn('target_node_id','text',(c)=>c.notNull().references('graph_nodes.id')).addColumn('token_hash','text',(c)=>c.notNull().unique()).addColumn('token_prefix','text',(c)=>c.notNull()).addColumn('visibility','text',(c)=>c.notNull().defaultTo('unlisted')).addColumn('expires_at','text').addColumn('revoked_at','text').addColumn('created_at','text',(c)=>c.notNull()).addColumn('updated_at','text',(c)=>c.notNull()).addColumn('deleted_at','text').execute()
  await db.schema.createIndex('idx_share_target').ifNotExists().on('share_links').columns(['user_id','target_node_id','deleted_at']).execute()
}
