import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { z } from 'zod'
import { ConvertInboxResponseSchema, CreateNoteRequestSchema, InboxItemResponseSchema, InboxListResponseSchema, LibraryOverviewResponseSchema, NoteResponseSchema, UpdateVideoLearningContextRequestSchema, UpdateVideoLearningContextResponseSchema, VideoListResponseSchema, VideoResponseSchema, SearchResponseSchema } from '@ttll/shared'
import { apiRequest } from './client'
const DeleteResponseSchema = z.object({ data: z.object({ deleted: z.literal(true) }) })
export function useInbox() { return useQuery({ queryKey: ['inbox'], queryFn: async () => (await apiRequest('/api/inbox?limit=50', undefined, InboxListResponseSchema)).data }) }
export function useInboxItem(id: string) { return useQuery({ queryKey: ['inbox', id], enabled: !!id, queryFn: async () => (await apiRequest(`/api/inbox/${id}`, undefined, InboxItemResponseSchema)).data }) }
export function useCreateInbox() { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: { sourceUrl?: string; sharedTitle?: string; sharedText?: string }) => (await apiRequest('/api/inbox', { method: 'POST', body: JSON.stringify(body) }, InboxItemResponseSchema)).data, onSuccess: () => qc.invalidateQueries({ queryKey: ['inbox'] }) }) }
export function useConvertInbox(id: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: { title?: string; quickNote?: string; topicIds?: string[]; skillIds?: string[]; tagIds?: string[]; progress?: string; learningState?: string }) => (await apiRequest(`/api/inbox/${id}/convert-to-video`, { method: 'POST', body: JSON.stringify(body) }, ConvertInboxResponseSchema)).data, onSuccess: () => { qc.invalidateQueries({ queryKey: ['inbox'] }); qc.invalidateQueries({ queryKey: ['videos'] }) } }) }
export function useDeleteInbox(id: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async () => (await apiRequest(`/api/inbox/${id}`, { method: 'DELETE' }, DeleteResponseSchema)).data, onSuccess: () => { qc.removeQueries({ queryKey: ['inbox', id] }); qc.invalidateQueries({ queryKey: ['inbox'] }) } }) }
export function useVideos() { return useQuery({ queryKey: ['videos'], queryFn: async () => (await apiRequest('/api/videos?limit=50', undefined, VideoListResponseSchema)).data }) }
export function useVideo(id: string) { return useQuery({ queryKey: ['video', id], enabled: !!id, queryFn: async () => (await apiRequest(`/api/videos/${id}`, undefined, VideoResponseSchema)).data }) }
export function useDeleteVideo() { const qc = useQueryClient(); return useMutation({ mutationFn: async (id: string) => (await apiRequest(`/api/videos/${id}`, { method: 'DELETE' }, DeleteResponseSchema)).data, onSuccess: (_, id) => { qc.removeQueries({ queryKey: ['video', id] }); qc.invalidateQueries({ queryKey: ['videos'] }); qc.invalidateQueries({ queryKey: ['library-overview'] }) } }) }
export function useLibraryOverview() { return useQuery({ queryKey: ['library-overview'], queryFn: async () => (await apiRequest('/api/library/overview', undefined, LibraryOverviewResponseSchema)).data }) }
export function useCreateNote() { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: unknown) => (await apiRequest('/api/library/notes', { method: 'POST', body: JSON.stringify(CreateNoteRequestSchema.parse(body)) }, NoteResponseSchema)).data, onSuccess: (_, input) => { const parsed = CreateNoteRequestSchema.parse(input); qc.invalidateQueries({ queryKey: ['video'] }); qc.invalidateQueries({ queryKey: ['library-overview'] }); qc.invalidateQueries({ queryKey: ['notes', parsed.parentNodeId] }) } }) }
export function useUpdateVideoLearningContext(id: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: unknown) => (await apiRequest(`/api/videos/${id}/learning-context`, { method: 'PUT', body: JSON.stringify(UpdateVideoLearningContextRequestSchema.parse(body)) }, UpdateVideoLearningContextResponseSchema)).data, onSuccess: (data) => { qc.setQueryData(['video', id], data); qc.invalidateQueries({ queryKey: ['library-overview'] }); qc.invalidateQueries({ queryKey: ['videos'] }) } }) }
export function useSearch(q: string) { return useQuery({ queryKey: ['search', q], enabled: q.trim().length >= 2, queryFn: async () => (await apiRequest(`/api/search?q=${encodeURIComponent(q)}&limit=50`, undefined, SearchResponseSchema)).data }) }
