import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ConvertInboxResponseSchema, InboxItemResponseSchema, InboxListResponseSchema, VideoListResponseSchema, VideoResponseSchema, SearchResponseSchema } from '@ttll/shared'
import { apiRequest } from './client'
export function useInbox() { return useQuery({ queryKey: ['inbox'], queryFn: async () => (await apiRequest('/api/inbox?limit=50', undefined, InboxListResponseSchema)).data }) }
export function useInboxItem(id: string) { return useQuery({ queryKey: ['inbox', id], enabled: !!id, queryFn: async () => (await apiRequest(`/api/inbox/${id}`, undefined, InboxItemResponseSchema)).data }) }
export function useCreateInbox() { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: { sourceUrl?: string; sharedTitle?: string; sharedText?: string }) => (await apiRequest('/api/inbox', { method: 'POST', body: JSON.stringify(body) }, InboxItemResponseSchema)).data, onSuccess: () => qc.invalidateQueries({ queryKey: ['inbox'] }) }) }
export function useConvertInbox(id: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: { title?: string; quickNote?: string; topicIds?: string[]; skillIds?: string[]; tagIds?: string[]; progress?: string; learningState?: string }) => (await apiRequest(`/api/inbox/${id}/convert-to-video`, { method: 'POST', body: JSON.stringify(body) }, ConvertInboxResponseSchema)).data, onSuccess: () => { qc.invalidateQueries({ queryKey: ['inbox'] }); qc.invalidateQueries({ queryKey: ['videos'] }) } }) }
export function useVideos() { return useQuery({ queryKey: ['videos'], queryFn: async () => (await apiRequest('/api/videos?limit=50', undefined, VideoListResponseSchema)).data }) }
export function useVideo(id: string) { return useQuery({ queryKey: ['video', id], enabled: !!id, queryFn: async () => (await apiRequest(`/api/videos/${id}`, undefined, VideoResponseSchema)).data }) }
export function useSearch(q: string) { return useQuery({ queryKey: ['search', q], enabled: q.trim().length >= 2, queryFn: async () => (await apiRequest(`/api/search?q=${encodeURIComponent(q)}&limit=50`, undefined, SearchResponseSchema)).data }) }
