import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { z } from 'zod'
import { AttachmentListResponseSchema, AttachmentResponseSchema, ConvertInboxResponseSchema, CreateNoteRequestSchema, InboxItemResponseSchema, InboxListResponseSchema, LibraryNodeResourcesResponseSchema, LibraryOverviewResponseSchema, NoteResponseSchema, UpdateVideoLearningContextRequestSchema, UpdateVideoLearningContextResponseSchema, VideoListResponseSchema, VideoResponseSchema, SearchResponseSchema, CreateTrainingSessionRequestSchema, TrainingInsightsResponseSchema, TrainingPracticeOptionsResponseSchema, TrainingSessionListResponseSchema, TrainingSessionResponseSchema, CompleteTrainingSessionRequestSchema, ReplaceRemainingBlocksRequestSchema, type CreateTrainingSessionRequest, type CompleteTrainingSessionRequest, type ReplaceRemainingBlocksRequest } from '@ttll/shared'
import { apiRequest, authenticatedBlob } from './client'
const DeleteResponseSchema = z.object({ data: z.object({ deleted: z.literal(true) }) })
export function useInbox() { return useQuery({ queryKey: ['inbox'], queryFn: async () => (await apiRequest('/api/inbox?limit=50', undefined, InboxListResponseSchema)).data }) }
export function useInboxItem(id: string) { return useQuery({ queryKey: ['inbox', id], enabled: !!id, queryFn: async () => (await apiRequest(`/api/inbox/${id}`, undefined, InboxItemResponseSchema)).data }) }
export function useCreateInbox() { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: { sourceUrl?: string; sharedTitle?: string; sharedText?: string }) => (await apiRequest('/api/inbox', { method: 'POST', body: JSON.stringify(body) }, InboxItemResponseSchema)).data, onSuccess: () => qc.invalidateQueries({ queryKey: ['inbox'] }) }) }
export function useConvertInbox(id: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: { title?: string; quickNote?: string; topicIds?: string[]; skillIds?: string[]; tagIds?: string[]; progress?: string; learningState?: string }) => (await apiRequest(`/api/inbox/${id}/convert-to-video`, { method: 'POST', body: JSON.stringify(body) }, ConvertInboxResponseSchema)).data, onSuccess: () => { qc.invalidateQueries({ queryKey: ['inbox'] }); qc.invalidateQueries({ queryKey: ['videos'] }) } }) }
export function useDeleteInbox(id: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async () => (await apiRequest(`/api/inbox/${id}`, { method: 'DELETE' }, DeleteResponseSchema)).data, onSuccess: () => { qc.removeQueries({ queryKey: ['inbox', id] }); qc.invalidateQueries({ queryKey: ['inbox'] }) } }) }
export function useVideos() { return useQuery({ queryKey: ['videos'], queryFn: async () => (await apiRequest('/api/videos?limit=50', undefined, VideoListResponseSchema)).data }) }
export function useVideo(id: string) { return useQuery({ queryKey: ['video', id], enabled: !!id, queryFn: async () => (await apiRequest(`/api/videos/${id}`, undefined, VideoResponseSchema)).data }) }
export function useDeleteVideo() { const qc = useQueryClient(); return useMutation({ mutationFn: async (id: string) => (await apiRequest(`/api/videos/${id}`, { method: 'DELETE' }, DeleteResponseSchema)).data, onSuccess: (_, id) => { qc.removeQueries({ queryKey: ['video', id] }); qc.invalidateQueries({ queryKey: ['videos'] }); qc.invalidateQueries({ queryKey: ['library-overview'] }) } }) }
export function useLibraryOverview() { return useQuery({ queryKey: ['library-overview'], queryFn: async () => (await apiRequest('/api/library/overview', undefined, LibraryOverviewResponseSchema)).data }) }
export function useSetTopicVisibility() { const qc = useQueryClient(); return useMutation({ mutationFn: async (input: { id: string; hidden: boolean }) => apiRequest(`/api/library/topics/${encodeURIComponent(input.id)}/visibility`, { method: 'PATCH', body: JSON.stringify({ hidden: input.hidden }) }, z.object({ data: z.unknown() })), onSuccess: () => qc.invalidateQueries({ queryKey: ['library-overview'] }) }) }
export function useLibraryNodeResources(nodeId: string) { return useQuery({ queryKey: ['library-node-resources', nodeId], enabled: !!nodeId, queryFn: async () => (await apiRequest(`/api/library/nodes/${encodeURIComponent(nodeId)}/resources`, undefined, LibraryNodeResourcesResponseSchema)).data }) }
export function useSetLibraryPin(nodeId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async (pinned: boolean) => apiRequest(`/api/library/nodes/${encodeURIComponent(nodeId)}/pin`, { method: 'PATCH', body: JSON.stringify({ pinned }) }, z.object({ data: z.object({ nodeId: z.string(), pinned: z.boolean() }) })), onSuccess: () => { qc.invalidateQueries({ queryKey: ['library-node-resources', nodeId] }); qc.invalidateQueries({ queryKey: ['library-overview'] }) } }) }
export function useAttachLibraryVideo(nodeId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async (videoId: string) => apiRequest(`/api/library/nodes/${encodeURIComponent(nodeId)}/videos/${encodeURIComponent(videoId)}`, { method: 'POST', body: '{}' }, z.object({ data: z.object({ edge: z.unknown(), video: z.unknown() }) })), onSuccess: () => { qc.invalidateQueries({ queryKey: ['library-node-resources', nodeId] }); qc.invalidateQueries({ queryKey: ['library-overview'] }) } }) }
export function useLinkPersonalDrillSkill(nodeId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async (skillNodeId: string) => apiRequest(`/api/library/nodes/${encodeURIComponent(nodeId)}/skills/${encodeURIComponent(skillNodeId)}`, { method: 'POST', body: '{}' }, z.object({ data: z.object({ edge: z.unknown() }) })), onSuccess: () => { qc.invalidateQueries({ queryKey: ['library-node-resources', nodeId] }); qc.invalidateQueries({ queryKey: ['training-options'] }) } }) }
export function useCreateNote() { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: unknown) => (await apiRequest('/api/library/notes', { method: 'POST', body: JSON.stringify(CreateNoteRequestSchema.parse(body)) }, NoteResponseSchema)).data, onSuccess: (_, input) => { const parsed = CreateNoteRequestSchema.parse(input); qc.invalidateQueries({ queryKey: ['video'] }); qc.invalidateQueries({ queryKey: ['library-overview'] }); qc.invalidateQueries({ queryKey: ['notes', parsed.parentNodeId] }) } }) }
export function useUpdateVideoLearningContext(id: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: unknown) => (await apiRequest(`/api/videos/${id}/learning-context`, { method: 'PUT', body: JSON.stringify(UpdateVideoLearningContextRequestSchema.parse(body)) }, UpdateVideoLearningContextResponseSchema)).data, onSuccess: (data) => { qc.setQueryData(['video', id], data); qc.invalidateQueries({ queryKey: ['library-overview'] }); qc.invalidateQueries({ queryKey: ['videos'] }) } }) }
export function useSearch(q: string) { return useQuery({ queryKey: ['search', q], enabled: q.trim().length >= 2, queryFn: async () => (await apiRequest(`/api/search?q=${encodeURIComponent(q)}&limit=50`, undefined, SearchResponseSchema)).data }) }

const trainingRange = (from: string, to: string) => `from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`
export function useTrainingSessions(from: string, to: string) { return useQuery({ queryKey: ['training-sessions', from, to], enabled: !!from && !!to, queryFn: async () => (await apiRequest(`/api/training/sessions?${trainingRange(from, to)}`, undefined, TrainingSessionListResponseSchema)).data }) }
export function useTrainingSession(id: string) { return useQuery({ queryKey: ['training-session', id], enabled: !!id, refetchInterval: (query) => query.state.data?.session.status === 'in_progress' ? 30_000 : false, queryFn: async () => (await apiRequest(`/api/training/sessions/${id}`, undefined, TrainingSessionResponseSchema)).data }) }
export function useTrainingPracticeOptions(skillId: string) { return useQuery({ queryKey: ['training-options', skillId], enabled: !!skillId, queryFn: async () => (await apiRequest(`/api/training/practice-options/${skillId}`, undefined, TrainingPracticeOptionsResponseSchema)).data }) }
export function useTrainingInsights(from: string, to: string) { return useQuery({ queryKey: ['training-insights', from, to], enabled: !!from && !!to, queryFn: async () => (await apiRequest(`/api/training/insights?${trainingRange(from, to)}`, undefined, TrainingInsightsResponseSchema)).data }) }
export function useCreateTrainingSession() { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: CreateTrainingSessionRequest) => (await apiRequest('/api/training/sessions', { method: 'POST', body: JSON.stringify(CreateTrainingSessionRequestSchema.parse(body)) }, TrainingSessionResponseSchema)).data, onSuccess: () => { qc.invalidateQueries({ queryKey: ['training-sessions'] }); qc.invalidateQueries({ queryKey: ['training-insights'] }) } }) }
export function useCopyTrainingSession(id: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: { scheduledDate: string; timeZone: string; title?: string }) => (await apiRequest(`/api/training/sessions/${id}/copy`, { method: 'POST', body: JSON.stringify(body) }, TrainingSessionResponseSchema)).data, onSuccess: () => qc.invalidateQueries({ queryKey: ['training-sessions'] }) }) }
export function useReplaceTrainingBlocks(id: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: ReplaceRemainingBlocksRequest) => (await apiRequest(`/api/training/sessions/${id}/remaining-blocks`, { method: 'PUT', body: JSON.stringify(ReplaceRemainingBlocksRequestSchema.parse(body)) }, TrainingSessionResponseSchema)).data, onSuccess: (data) => { qc.setQueryData(['training-session', id], data); qc.invalidateQueries({ queryKey: ['training-sessions'] }) } }) }
export function useStartTrainingSession(id: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async () => (await apiRequest(`/api/training/sessions/${id}/start`, { method: 'POST', body: '{}' }, TrainingSessionResponseSchema)).data, onSuccess: (data) => { qc.setQueryData(['training-session', id], data); qc.invalidateQueries({ queryKey: ['training-sessions'] }) } }) }
export function useTransitionTrainingBlock(id: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async (input: { blockId: string; action: 'start'|'pause'|'resume'|'complete'|'skip'|'add_time'; additionalSeconds?: number }) => (await apiRequest(`/api/training/sessions/${id}/blocks/${input.blockId}/transition`, { method: 'POST', body: JSON.stringify({ action: input.action, additionalSeconds: input.additionalSeconds }) }, TrainingSessionResponseSchema)).data, onSuccess: (data) => { qc.setQueryData(['training-session', id], data); qc.invalidateQueries({ queryKey: ['training-sessions'] }); qc.invalidateQueries({ queryKey: ['training-insights'] }) } }) }
export function useCompleteTrainingSession(id: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: CompleteTrainingSessionRequest) => (await apiRequest(`/api/training/sessions/${id}/complete`, { method: 'POST', body: JSON.stringify(CompleteTrainingSessionRequestSchema.parse(body)) }, TrainingSessionResponseSchema)).data, onSuccess: (data) => { qc.setQueryData(['training-session', id], data); qc.invalidateQueries({ queryKey: ['training-sessions'] }); qc.invalidateQueries({ queryKey: ['training-insights'] }) } }) }
export function useDeleteTrainingSession() { const qc = useQueryClient(); return useMutation({ mutationFn: async (id: string) => (await apiRequest(`/api/training/sessions/${id}`, { method: 'DELETE' }, DeleteResponseSchema)).data, onSuccess: (_, id) => { qc.removeQueries({ queryKey: ['training-session', id] }); qc.invalidateQueries({ queryKey: ['training-sessions'] }); qc.invalidateQueries({ queryKey: ['training-insights'] }) } }) }
export function useAttachments(parentNodeId: string) { return useQuery({ queryKey: ['pictures', parentNodeId], enabled: !!parentNodeId, queryFn: async () => (await apiRequest(`/api/pictures?parentNodeId=${encodeURIComponent(parentNodeId)}`, undefined, AttachmentListResponseSchema)).data }) }
export function useAttachmentBlob(id: string) { return useQuery({ queryKey: ['picture-content', id], queryFn: () => authenticatedBlob(`/api/pictures/${encodeURIComponent(id)}/content`), staleTime: Infinity }) }
export function useCreateAttachment(parentNodeId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async (file: File) => { const form = new FormData(); form.set('parentNodeId', parentNodeId); form.set('picture', file); return (await apiRequest('/api/pictures', { method: 'POST', body: form }, AttachmentResponseSchema)).data }, onSuccess: () => qc.invalidateQueries({ queryKey: ['pictures', parentNodeId] }) }) }
export function useDeleteAttachment(parentNodeId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: async (id: string) => (await apiRequest(`/api/pictures/${encodeURIComponent(id)}`, { method: 'DELETE' }, DeleteResponseSchema)).data, onSuccess: (_, id) => { qc.removeQueries({ queryKey: ['picture-content', id] }); qc.invalidateQueries({ queryKey: ['pictures', parentNodeId] }) } }) }
const CreatedDrillResponseSchema = z.object({ data: z.object({ id: z.string(), node_id: z.string(), title: z.string(), description: z.string().nullable() }) })
export function useCreateLibraryDrill() { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: { description: string }) => (await apiRequest('/api/library/drills', { method: 'POST', body: JSON.stringify(body) }, CreatedDrillResponseSchema)).data, onSuccess: () => qc.invalidateQueries({ queryKey: ['library-overview'] }) }) }
