import { Layout } from '../components/Layout'
import { useRoute } from './router'
import { Home } from '../features/Home'
import { AddVideo } from '../features/videos/AddVideo'
import { InboxList } from '../features/inbox/InboxList'
import { OrganizeInbox } from '../features/inbox/OrganizeInbox'
import { Library } from '../features/library/Library'
import { VideoDetail } from '../features/videos/VideoDetail'
import { SearchPage } from '../features/search/SearchPage'
import { Settings } from '../features/Settings'
import { Login } from '../features/Login'
import { useAuth } from '../lib/auth/AuthProvider'
export function App() { const { path, navigate } = useRoute(); const auth=useAuth(); const base = path.split('?')[0]; if(auth.isLoading)return <main className="login-page"><div className="login-card">Checking your session…</div></main>; if(auth.isConfigured&&!auth.user)return <Login/>; let page: React.ReactNode; if (base === '/') page=<Home navigate={navigate}/>; else if (base === '/videos/new') page=<AddVideo navigate={navigate}/>; else if (base === '/inbox') page=<InboxList navigate={navigate}/>; else if (base.startsWith('/quick-save/')) page=<OrganizeInbox quick id={base.split('/')[2]} navigate={navigate}/>; else if (base.startsWith('/inbox/')) page=<OrganizeInbox id={base.split('/')[2]} navigate={navigate}/>; else if (base === '/library') page=<Library navigate={navigate}/>; else if (base.startsWith('/videos/')) page=<VideoDetail id={base.split('/')[2]}/>; else if (base === '/search') page=<SearchPage navigate={navigate}/>; else page=<Settings/>; return <Layout path={base} navigate={navigate}>{page}</Layout> }
