import type { EdgeType } from './edgeTypes'
import type { NodeType } from './nodeTypes'

export const TABLE_TENNIS_TOPICS = [
  'Fundamentals', 'Serve', 'Receive', 'Spin', 'Forehand', 'Backhand', 'Footwork',
  'Defense', 'Tactics', 'Doubles', 'Training & Drills', 'Match Analysis',
  'Physical Training', 'Mental Game', 'Equipment', 'Rules & Officiating',
  'Para Table Tennis', 'Coaching'
] as const

export const TABLE_TENNIS_SKILLS = [
  { name: 'Ready Position', topic: 'Fundamentals' },
  { name: 'Shakehand Grip', topic: 'Fundamentals' },
  { name: 'Penhold Grip', topic: 'Fundamentals' },
  { name: 'Racket Angle Control', topic: 'Fundamentals' },
  { name: 'Ball Timing', topic: 'Fundamentals' },
  { name: 'Contact Point Control', topic: 'Fundamentals' },
  { name: 'Placement Control', topic: 'Fundamentals' },
  { name: 'Rally Consistency', topic: 'Fundamentals' },
  { name: 'Recovery After Stroke', topic: 'Fundamentals' },
  { name: 'Backspin Serve', topic: 'Serve' },
  { name: 'No-Spin Serve', topic: 'Serve' },
  { name: 'Topspin Serve', topic: 'Serve' },
  { name: 'Sidespin Serve', topic: 'Serve' },
  { name: 'Pendulum Serve', topic: 'Serve' },
  { name: 'Reverse Pendulum Serve', topic: 'Serve' },
  { name: 'Tomahawk Serve', topic: 'Serve' },
  { name: 'Backhand Serve', topic: 'Serve' },
  { name: 'High-Toss Serve', topic: 'Serve' },
  { name: 'Hook Serve', topic: 'Serve' },
  { name: 'Shovel Serve', topic: 'Serve' },
  { name: 'Fast Long Serve', topic: 'Serve' },
  { name: 'Short Serve', topic: 'Serve' },
  { name: 'Half-Long Serve', topic: 'Serve' },
  { name: 'Serve Placement', topic: 'Serve' },
  { name: 'Serve Variation and Disguise', topic: 'Serve' },
  { name: 'Legal Service Action', topic: 'Serve' },
  { name: 'Reading Serve Spin', topic: 'Receive' },
  { name: 'Short Push Receive', topic: 'Receive' },
  { name: 'Long Push Receive', topic: 'Receive' },
  { name: 'Banana Flick', topic: 'Receive' },
  { name: 'Forehand Flick Receive', topic: 'Receive' },
  { name: 'Backhand Flick Receive', topic: 'Receive' },
  { name: 'Receive With Topspin', topic: 'Receive' },
  { name: 'Receive With Chop', topic: 'Receive' },
  { name: 'Drop Shot Receive', topic: 'Receive' },
  { name: 'Aggressive Long-Serve Receive', topic: 'Receive' },
  { name: 'Receive Placement', topic: 'Receive' },
  { name: 'Receive Against No-Spin', topic: 'Receive' },
  { name: 'Receive Against Sidespin', topic: 'Receive' },
  { name: 'Generating Topspin', topic: 'Spin' },
  { name: 'Generating Backspin', topic: 'Spin' },
  { name: 'Generating Sidespin', topic: 'Spin' },
  { name: 'Reading Incoming Spin', topic: 'Spin' },
  { name: 'Counteracting Spin', topic: 'Spin' },
  { name: 'Using Spin Reversal', topic: 'Spin' },
  { name: 'Varying Spin and Speed', topic: 'Spin' },
  { name: 'Forehand Drive', topic: 'Forehand' },
  { name: 'Forehand Counterhit', topic: 'Forehand' },
  { name: 'Forehand Topspin', topic: 'Forehand' },
  { name: 'Forehand Loop Against Backspin', topic: 'Forehand' },
  { name: 'Forehand Loop Against Topspin', topic: 'Forehand' },
  { name: 'Forehand Counter-Topspin', topic: 'Forehand' },
  { name: 'Forehand Push', topic: 'Forehand' },
  { name: 'Forehand Flick', topic: 'Forehand' },
  { name: 'Forehand Block', topic: 'Forehand' },
  { name: 'Forehand Smash', topic: 'Forehand' },
  { name: 'Forehand Lob', topic: 'Forehand' },
  { name: 'Forehand Chop', topic: 'Forehand' },
  { name: 'Backhand Drive', topic: 'Backhand' },
  { name: 'Backhand Counterhit', topic: 'Backhand' },
  { name: 'Backhand Loop', topic: 'Backhand' },
  { name: 'Backhand Loop Against Backspin', topic: 'Backhand' },
  { name: 'Backhand Loop Against Topspin', topic: 'Backhand' },
  { name: 'Backhand Counter-Topspin', topic: 'Backhand' },
  { name: 'Backhand Push', topic: 'Backhand' },
  { name: 'Backhand Flick', topic: 'Backhand' },
  { name: 'Backhand Block', topic: 'Backhand' },
  { name: 'Backhand Punch', topic: 'Backhand' },
  { name: 'Backhand Chop', topic: 'Backhand' },
  { name: 'Backhand Lob', topic: 'Backhand' },
  { name: 'Split Step', topic: 'Footwork' },
  { name: 'One-Step Footwork', topic: 'Footwork' },
  { name: 'Side-Step Footwork', topic: 'Footwork' },
  { name: 'Shuffle-Step Footwork', topic: 'Footwork' },
  { name: 'Crossover Footwork', topic: 'Footwork' },
  { name: 'Pivot Footwork', topic: 'Footwork' },
  { name: 'In-and-Out Footwork', topic: 'Footwork' },
  { name: 'Forehand–Backhand Transition', topic: 'Footwork' },
  { name: 'Wide-Ball Recovery', topic: 'Footwork' },
  { name: 'Third-Ball Attack', topic: 'Tactics' },
  { name: 'Falkenberg Footwork', topic: 'Footwork' },
  { name: 'Chop Defense', topic: 'Defense' },
  { name: 'Block Defense', topic: 'Defense' },
  { name: 'Lob Defense', topic: 'Defense' },
  { name: 'Fishing Defense', topic: 'Defense' },
  { name: 'Counterattack From Defense', topic: 'Defense' },
  { name: 'Twiddling the Racket', topic: 'Defense' },
  { name: 'Playing With Long Pimples', topic: 'Defense' },
  { name: 'Playing With Short Pimples', topic: 'Defense' },
  { name: 'Playing With Anti-Spin', topic: 'Defense' },
  { name: 'Serve-and-Attack Pattern', topic: 'Tactics' },
  { name: 'Fifth-Ball Attack', topic: 'Tactics' },
  { name: 'Short-Short-Long Pattern', topic: 'Tactics' },
  { name: 'Opening Against Backspin', topic: 'Tactics' },
  { name: 'Changing Placement', topic: 'Tactics' },
  { name: 'Changing Pace', topic: 'Tactics' },
  { name: 'Changing Spin', topic: 'Tactics' },
  { name: 'Playing the Elbow', topic: 'Tactics' },
  { name: 'Controlling Table Position', topic: 'Tactics' },
  { name: 'Switching From Passive to Active Play', topic: 'Tactics' },
  { name: 'Playing Against Attackers', topic: 'Tactics' },
  { name: 'Playing Against Defenders', topic: 'Tactics' },
  { name: 'Playing Against Long Pimples', topic: 'Tactics' },
  { name: 'Playing Against Short Pimples', topic: 'Tactics' },
  { name: 'Playing Against Anti-Spin', topic: 'Tactics' },
  { name: 'Left-Handed Opponent Tactics', topic: 'Tactics' },
  { name: 'Doubles Service Placement', topic: 'Doubles' },
  { name: 'Doubles Receive Placement', topic: 'Doubles' },
  { name: 'Doubles Movement Rotation', topic: 'Doubles' },
  { name: 'Doubles Partner Communication', topic: 'Doubles' },
  { name: 'Doubles Tactical Sequencing', topic: 'Doubles' },
  { name: 'Left–Right-Handed Doubles Partnership', topic: 'Doubles' },
  { name: 'Regularity Training', topic: 'Training & Drills' },
  { name: 'Multiball Training', topic: 'Training & Drills' },
  { name: 'Serve Practice Design', topic: 'Training & Drills' },
  { name: 'Receive Practice Design', topic: 'Training & Drills' },
  { name: 'Footwork Drill Design', topic: 'Training & Drills' },
  { name: 'Random Practice', topic: 'Training & Drills' },
  { name: 'Match-Simulation Practice', topic: 'Training & Drills' },
  { name: 'Training Load Planning', topic: 'Training & Drills' },
  { name: 'Warm-Up Routine', topic: 'Physical Training' },
  { name: 'Cool-Down Routine', topic: 'Physical Training' },
  { name: 'Mobility and Flexibility', topic: 'Physical Training' },
  { name: 'Lower-Body Strength', topic: 'Physical Training' },
  { name: 'Core Strength', topic: 'Physical Training' },
  { name: 'Speed and Agility', topic: 'Physical Training' },
  { name: 'Aerobic and Anaerobic Conditioning', topic: 'Physical Training' },
  { name: 'Shoulder and Wrist Conditioning', topic: 'Physical Training' },
  { name: 'Injury Prevention', topic: 'Physical Training' },
  { name: 'Recovery and Sleep', topic: 'Physical Training' },
  { name: 'Competition Nutrition and Hydration', topic: 'Physical Training' },
  { name: 'Pre-Match Routine', topic: 'Mental Game' },
  { name: 'Goal Setting', topic: 'Mental Game' },
  { name: 'Focus and Refocusing', topic: 'Mental Game' },
  { name: 'Breathing and Arousal Control', topic: 'Mental Game' },
  { name: 'Positive Self-Talk', topic: 'Mental Game' },
  { name: 'Imagery and Visualization', topic: 'Mental Game' },
  { name: 'Handling Match Pressure', topic: 'Mental Game' },
  { name: 'Recovering After Mistakes', topic: 'Mental Game' },
  { name: 'Between-Game Adjustment', topic: 'Mental Game' },
  { name: 'Scouting an Opponent', topic: 'Match Analysis' },
  { name: 'Identifying Serve and Receive Patterns', topic: 'Match Analysis' },
  { name: 'Rally Pattern Analysis', topic: 'Match Analysis' },
  { name: 'Unforced Error Analysis', topic: 'Match Analysis' },
  { name: 'Video Self-Analysis', topic: 'Match Analysis' },
  { name: 'Post-Match Review', topic: 'Match Analysis' },
  { name: 'Choosing a Blade', topic: 'Equipment' },
  { name: 'Choosing Forehand Rubber', topic: 'Equipment' },
  { name: 'Choosing Backhand Rubber', topic: 'Equipment' },
  { name: 'Understanding Sponge Hardness and Thickness', topic: 'Equipment' },
  { name: 'Understanding Pimpled and Anti-Spin Rubbers', topic: 'Equipment' },
  { name: 'Racket Assembly and Gluing', topic: 'Equipment' },
  { name: 'Racket Care and Cleaning', topic: 'Equipment' },
  { name: 'Adapting to Ball, Table, and Flooring', topic: 'Equipment' },
  { name: 'Scoring and Game Structure', topic: 'Rules & Officiating' },
  { name: 'Service Rules', topic: 'Rules & Officiating' },
  { name: 'Doubles Service Order', topic: 'Rules & Officiating' },
  { name: 'Let and Point Rules', topic: 'Rules & Officiating' },
  { name: 'Expedite System', topic: 'Rules & Officiating' },
  { name: 'Timeout and Interval Rules', topic: 'Rules & Officiating' },
  { name: 'Racket and Equipment Rules', topic: 'Rules & Officiating' },
  { name: 'Basic Umpiring', topic: 'Rules & Officiating' },
  { name: 'Wheelchair Table Tennis Movement', topic: 'Para Table Tennis' },
  { name: 'Standing Para Table Tennis Movement', topic: 'Para Table Tennis' },
  { name: 'Adaptive Grip and Racket Use', topic: 'Para Table Tennis' },
  { name: 'Para Service and Receive Adaptations', topic: 'Para Table Tennis' },
  { name: 'Para Table Tennis Classification Awareness', topic: 'Para Table Tennis' },
  { name: 'Inclusive Practice Design', topic: 'Para Table Tennis' },
  { name: 'Technical Observation and Feedback', topic: 'Coaching' },
  { name: 'Session Planning', topic: 'Coaching' },
  { name: 'Skill Progression Design', topic: 'Coaching' },
  { name: 'Error Diagnosis and Correction', topic: 'Coaching' },
  { name: 'Multiball Feeding', topic: 'Coaching' },
  { name: 'Coaching During Competition', topic: 'Coaching' },
  { name: 'Safe and Ethical Coaching', topic: 'Coaching' },
  { name: 'Adapting Coaching to Age and Ability', topic: 'Coaching' }
] as const

export const NOTE_PARENT_NODE_TYPES = ['video', 'skill', 'topic', 'drill', 'mistake'] as const satisfies readonly NodeType[]

type Pair = readonly [NodeType, NodeType]
const pairs = (...values: Pair[]) => values
const sameTypePairs = (...types: NodeType[]) => types.map((type) => [type, type] as const)

export const ONTOLOGY_RELATIONSHIPS = {
  belongs_to: pairs(['video', 'topic'], ['skill', 'topic'], ['topic', 'topic']),
  contains: pairs(
    ['learning_path', 'video'], ['learning_path', 'skill'], ['learning_path', 'drill'], ['learning_path', 'note'],
    ['collection', 'video'], ['collection', 'skill'], ['collection', 'drill'], ['collection', 'note']
  ),
  explains: pairs(['video', 'skill'], ['note', 'skill']),
  demonstrates: pairs(['video', 'skill']),
  practices: pairs(['drill', 'skill']),
  drill_for: pairs(['drill', 'skill'], ['drill', 'video']),
  related_to: pairs(...sameTypePairs('video', 'skill', 'topic', 'drill')),
  requires: pairs(['skill', 'skill']),
  prerequisite_of: pairs(['skill', 'skill']),
  common_mistake_for: pairs(['mistake', 'skill']),
  enables: pairs(['skill', 'skill']),
  mentions: pairs(['note', 'video'], ['note', 'skill'], ['note', 'topic'], ['note', 'drill'], ['note', 'mistake']),
  contrasts_with: pairs(['skill', 'skill'], ['video', 'video']),
  saved_from: pairs(['video', 'source']),
  created_by: pairs(['video', 'creator']),
  tagged_with: pairs(['video', 'tag'], ['skill', 'tag'], ['note', 'tag'], ['drill', 'tag'], ['mistake', 'tag'], ['learning_path', 'tag']),
  copied_from: pairs(['video', 'video'], ['skill', 'skill'], ['drill', 'drill']),
  forked_from: pairs(['video', 'video'], ['skill', 'skill'], ['drill', 'drill'])
} as const satisfies Record<EdgeType, readonly Pair[]>

export function isAllowedRelationship(source: NodeType, target: NodeType, edgeType: EdgeType): boolean {
  return (ONTOLOGY_RELATIONSHIPS[edgeType] as readonly Pair[]).some(([allowedSource, allowedTarget]) => allowedSource === source && allowedTarget === target)
}
